alias: "TrueNAS Scheduled Backup"
description: "Start the TrueNAS Backup add-on"
trigger:
  - platform: time
    at: "02:00:00"
action:
  - service: hassio.addon_start
    data:
      addon: "local_truenas_backup"
mode: single
