name: Build & Push GHCR images

on:
  push:
    branches: [main]
    paths-ignore:
      - '**.md'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        arch: [amd64, armv7, armhf, aarch64, i386]
        include:
          - arch: amd64     # 64-bit x86
            platform: linux/amd64
          - arch: armv7     # Raspberry Pi 32-bit
            platform: linux/arm/v7
          - arch: armhf     # old RPi/BeagleBone
            platform: linux/arm/v6
          - arch: aarch64   # 64-bit ARM
            platform: linux/arm64
          - arch: i386
            platform: linux/386

    steps:
      - name: 取出程式碼
        uses: actions/checkout@v4

      - name: 安裝 QEMU（跨架構模擬）
        uses: docker/setup-qemu-action@v3

      - name: 啟用 buildx
        uses: docker/setup-buildx-action@v3

      - name: 登入 GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 建置並推送單架構映像
        uses: docker/build-push-action@v5
        with:
          context: ./addon
          platforms: ${{ matrix.platform }}
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/truenas_backup-${{ matrix.arch }}:latest
            ghcr.io/${{ github.repository_owner }}/truenas_backup-${{ matrix.arch }}:${{ github.sha }}
            ghcr.io/${{ github.repository_owner }}/truenas_backup-${{ matrix.arch }}:1.0.0
